Update update_discord_with_uptime_graph.yml

diff --git a/.github/workflows/update_discord_with_uptime_graph.yml b/.github/workflows/update_discord_with_uptime_graph.yml
--- a/.github/workflows/update_discord_with_uptime_graph.yml
+++ b/.github/workflows/update_discord_with_uptime_graph.yml
@@ -5,7 +5,7 @@ on:
     branches:
       - main
   schedule:
-    - cron: '*/1 * * * *'
+    - cron: '*/5 * * * *'
 
 jobs:
   send_discord_message:
@@ -14,6 +14,10 @@ jobs:
     steps:
     - name: Checkout code
       uses: actions/checkout@v2
+
+    - name: Install dependencies
+      run: |
+        sudo apt-get install -y jq pup
 
     - name: Fetch status page content
       id: fetch_status
@@ -30,7 +34,7 @@ jobs:
         operational=$(echo "$status" | grep -o 'All systems operational' || true)
         partial=$(echo "$status" | grep -o 'Partial Outage' || true)
         outage=$(echo "$status" | grep -o 'Outage detected' || true)
-        graph_url=$(echo "$status" | grep -oP '(?<=<img src=")[^"]*uptime-graph[^"]*' || true)
+        graph_url=$(echo "$status" | pup 'img[src*="uptime-graph"] attr{src}' | head -n 1 || true)
         echo "Operational: $operational"
         echo "Partial: $partial"
         echo "Outage: $outage"
@@ -107,6 +111,9 @@ jobs:
              $DISCORD_WEBHOOK_URL)
         echo "Discord response status code: $response"
         if [ "$response" -ne 204 ]; then
+          echo "Failed to send message to Discord"
+          exit 1
+
    
 
 
